#
spring.profiles.active=dev
#
spring.output.ansi.enabled=ALWAYS
logging.level.root=WARN
logging.level.es.upm.miw=DEBUG
# Server web ----------------------------------------------
spring.jackson.default-property-inclusion=NON_NULL
# Application http://**/actuator/info ---------------------
management.endpoints.web.exposure.include=health,info
info.app.artifact=@project.artifactId@
info.app.version=@project.version@
info.app.build=@maven.build.timestamp@
#JWT  -----------------------------------------------------
miw.jwt.expire=3600
miw.jwt.issuer=es-upm-upm

#HAPI
miw.hapi.url=http://localhost:8080/fhir

#Azure
miw.azure.url=https://login.microsoftonline.com/1b4b8bc5-cd92-4e2f-b217-6fd66d4f90dc/oauth2/token
miw.azure.resource=https://tfm.azurehealthcareapis.com
miw.azure.id=1405dd49-0327-492b-9c51-8c2a2fbb5784
miw.azure.secret=vwq8Q~x8JkJuuHDwReKp~cOs62MK~qDmjAV~Zc5q
