#Port
server.port=8082
#JWT  -----------------------------------------------------
miw.jwt.secret=secret to test
#Components
miw.healthtracker.user=http://localhost:8081
miw.healthtracker.panel=http://localhost:4200
miw.healthtracker.fhir=

